// vuejs/src/components/Technos.vue
<template xmlns:v-on="http://www.w3.org/1999/xhtml">
  <div id="technos">
    <div class="wrapper">
      <div class="filters">
        <i class="glyphicon glyphicon-th-list"></i>
        <span v-for="(filter, index) in filters">
          <span class="filter" v-on:click="filterTech(filter)" :class="{ active: activeFilter === filter.value }">
            {{filter.label}}
          </span> <span v-if="index !== filters.length - 1">/</span>
        </span>
      </div>
      <div class="techs">
        <techno v-for="(techno, index) in technos"
                :key="index"
                :id="`techno-${index}`"
                class="tech"
                :class="[{disabled: techno.disabled}, (techno.position.base === 6) ? 'even' : 'odd']"
                :techno="techno"></techno>
      </div>
    </div>
  </div>
</template>
<script>
  import technos from 'json-loader!yaml-loader!../assets/technos.yml';
  import Techno from './Techno.vue';

  class TechnoPosition {
    constructor() {
      this.row = 0;
      this.base = 6;
      this.loopIndex = -1;
    }

    getBase() {
      let addClear = false;
      this.loopIndex++;
      if(this.loopIndex === this.base) {
        this.base = (this.base === 6) ? 5 : 6;
        addClear = true;
        this.row++;
        this.loopIndex = 0;
      }

      return {
        base:this.base,
        row: this.row,
        addClear: addClear
      };
    }
  }

  const filters = [
    { value: 'js', label: 'Javascript', tags: new Set(['js']) },
    { value: 'dev', label: 'Development', tags: new Set(['dev']) },
    { value: 'data', label: 'Data', tags: new Set(['data']) },
    { value: 'inte', label: 'Integration', tags: new Set(['inte', 'mobile']) },
  ];

  export default {
    name: 'technos',
    components: {
      Techno
    },
    data() {
      return {
        filters,
        activeFilter: null,
        technoPosition: new TechnoPosition()
      }
    },
    computed: {
      technos: function() {
        return technos.map((techno, index) => {
          techno.position = this.technoPosition.getBase();
          techno.last = index === technos.length - 1;
          return techno;
        });
      }
    },
    methods: {
      filterTech(filter) {
        if(!this.isSameFilter(filter.value)) {
          this.activeFilter = filter.value;
          this.setTechnosState(filter.tags);
        }
      },
      isSameFilter(filter) {
        const isSameFilter = this.activeFilter === filter;
        if (isSameFilter) {
          this.technos.map(techno => {
            techno.disabled = false;
          });
          this.activeFilter = null;
        }
        return isSameFilter;
      },
      setTechnosState(tags) {
        this.technos.map(techno => {
          const commonTags = [...techno.tags].filter(x => tags.has(x));
          techno.disabled = !commonTags.length;
        });
      }
    }
  };
</script>
<style lang="scss">
  @import "../variables";

  #technos {
    width: 100%;
    overflow-y: hidden;
  }

  .wrapper{
    padding: 40px 20px;
    width: 904px;
    margin: 0 auto;
  }

  .filters{
    font-size: 20px;
    text-transform: uppercase;
    color: #DDDDDD;
    text-align: center;
    font-family: $open;
    margin-bottom: 20px;
    i{
      color: $orange;
      font-size: 30px;
      position: relative;
      top: 7px;
      margin-right: 20px;
    }
    .filter{
      &.caption{
        color: #333;
      }
      transition: all .3s ease 0s;
      &.active,&:hover{
        color: $orange;
      }
      cursor: pointer;
    }
  }

  .techs{
    position: relative;
    top: 20px;

    .tech{

      width: $techW;
      height: $techH;
      margin: 0px 6px;
      display: inline-block;
      vertical-align: top;
      font-weight: 300;
      position: relative;
      transition: all .2s;

      &.disabled{
        opacity: .2;
      }

      &.odd{
        left:($techW/2)+6;
      }
    }
  }

  @media screen and (max-width: 1000px){
    .wrapper {
      display: none;
    }
  }

</style>

// angular/src/app/technos/technos.component.ts
import { Component } from '@angular/core';
import { TechnoComponent } from './techno/techno.component';
import { TechnoPosition } from "./techno/techno-position";
const technosData = require('json-loader!yaml-loader!./technos.yml');

@Component({
  selector: 'app-technos',
  templateUrl: './technos.component.html',
  styleUrls: ['./technos.component.scss'],
  viewProviders: [TechnoPosition],
})
export class TechnosComponent{
  technos: Array<TechnoComponent> = [];
  filter: string;

  constructor() {
    technosData.forEach(techno => {
      this.technos.push(techno);
    });
  }

  techFilter(event, filter) {
    if(!this.isSameFilter(filter)) {
      this.filter = filter;
      let tags = this.getTagsFromFilter(filter);
      this.setTechnosState(tags);
    }
  }

  private setTechnosState(tags: Set<String>) {
    this.technos.map(techno => {
      let commonTags = [...techno.tags].filter(x => tags.has(x));
      techno.disabled = (commonTags.length <= 0);
    });
  }

  private getTagsFromFilter(filter) {
    let tags = [];
    switch(filter){
      case 'js':
        tags = ['js'];
        break;
      case 'dev':
        tags = ['dev'];
        break;
      case 'data':
        tags = ['data'];
        break;
      case 'inte':
        tags = ['inte','mobile'];
        break;
    }

    return new Set(tags);
  }
  private isSameFilter(filter) {
    let isSameFilter = this.filter === filter;
    if(isSameFilter) {
      this.technos.map(techno => {
        techno.disabled = false;
      });
      this.filter = null;
    }
    return isSameFilter;
  }

}

<div class="wrapper">
  <div class="filters">
    <i class="glyphicon glyphicon-th-list"></i>
    <span class="js" (click)="techFilter($event, 'js')" [ngClass]="{active: (filter === 'js')}">{{ 'JS' | translate }}</span> /
    <span class="dev" (click)="techFilter($event, 'dev')" [ngClass]="{active: (filter === 'dev')}">{{ 'DEV' | translate }}</span> /
    <span class="data" (click)="techFilter($event, 'data')" [ngClass]="{active: (filter === 'data')}">{{ 'DATA' | translate }}</span> /
    <span class="inte" (click)="techFilter($event, 'inte')" [ngClass]="{active: (filter === 'inte')}">{{ 'INTE' | translate }}</span>
  </div>
  <div class="techs">
    <app-techno id="techno-{{index}}" class="tech" [ngClass]="{disabled: techno.disabled}"
            *ngFor="let techno of technos; let index = index; let last = last;"
            [index]="index"
            [last]="last"
            [techno]="techno"></app-techno>
  </div>
</div>
