// vuejs/src/components/LinkTooltip.vue
<template xmlns:v-on="http://www.w3.org/1999/xhtml">
  <div class="nav-link" :class="title">
    <a href="#" class="link" :title="title" v-on:mouseenter="displayTooltip()" v-on:mouseleave="hideTooltip()"></a>
    <div class="tooltip right" v-if="isTooltipVisible" role="tooltip">
      <div class="tooltip-arrow"></div>
      <div class="tooltip-inner">{{title}}</div>
    </div>
  </div>
</template>
<script>
  export default {
    name: 'linkTooltip',
    props: ['title'],
    data() {
      return {
        isTooltipVisible: false
      }
    },
    methods: {
      displayTooltip() {
        this.isTooltipVisible = true;
      },

      hideTooltip() {
        this.isTooltipVisible = false;
      }
    }
  }
</script>
<style lang="scss">
  .tooltip {
    right: 0;
    transform: translateX(100%) translateY(-50%);
    top: 50%;
    opacity: 1;
  }

  .link {
    display: block;
    width: 100%;
    height: 100%;
  }

</style>

// src/app/link-tooltip/link-tooltip.component.ts
import {Component, Input, EventEmitter, Output} from '@angular/core';

@Component({
  selector: 'app-link-tooltip',
  templateUrl: './link-tooltip.component.html',
  styles: [require('./link-tooltip.component.scss')]
})
export class LinkTooltipComponent {

  isTooltipVisible: boolean = false;
  @Input('title') title: string;
  @Output() onClicked = new EventEmitter<void>();

  constructor() { }

  displayTooltip() {
    this.isTooltipVisible = true
  }

  hideTooltip() {
    this.isTooltipVisible = false
  }
}

<a href="#" class="link" (click)="onClicked.emit($event)" (mouseenter)="displayTooltip()" (mouseleave)="hideTooltip()"></a>
<div class="tooltip fade right in" [ngClass]="{'in': isTooltipVisible }" role="tooltip">
  <div class="tooltip-arrow"></div>
  <div class="tooltip-inner">{{title | translate}}</div>
</div>
